@extends('layouts.public')
@section('title', $product->name.' — Família Gundja')
@section('content')
<section class="container section"><div class="breadcrumbs"><a href="/produtos">Catálogo</a> / {{ $product->name }}</div><div class="detail-grid">
<div><div class="detail-image">@if($product->productImages->isNotEmpty())<img src="{{ Storage::disk('public')->url($product->productImages->sortBy('sort_order')->first()->path) }}" alt="{{ $product->name }}">@else<span class="product-placeholder">g+</span>@endif</div>@foreach($product->productImages->sortBy('sort_order')->skip(1) as $image)<img class="image-preview" src="{{ Storage::disk('public')->url($image->path) }}" alt="{{ $image->alt }}">@endforeach</div>
<div><span class="eyebrow">{{ $product->segment->name }} / {{ $product->category->name }}</span><h1 style="font-size:42px">{{ $product->name }}</h1><p>{{ $product->short_description }}</p><div class="detail-price">{{ $product->price !== null ? number_format((float)($product->sale_price ?? $product->price),2,',','.').' Kz' : 'Preço sob consulta' }}</div>
@if($product->purchase_mode !== 'catalog_only' && $locations->isNotEmpty())
<form method="post" action="/pedidos">@csrf<input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', $key) }}"><input type="hidden" name="segment_id" value="{{ $product->segment_id }}"><input type="hidden" name="items[0][product_id]" value="{{ $product->id }}">
<div class="form-grid"><div class="field"><label for="branch_id">Filial</label><select id="branch_id" name="branch_id" required>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('branch_id') == $location->id)>{{ $location->name }}</option>@endforeach</select></div><div class="field"><label for="quantity">Quantidade</label><input id="quantity" type="number" name="items[0][quantity]" value="{{ old('items.0.quantity', 1) }}" min="{{ $product->unit === 'unit' ? '1' : '0.001' }}" max="9999" step="{{ $product->unit === 'unit' ? '1' : '0.001' }}" required></div>
<div class="field"><label for="customer_name">O seu nome</label><input id="customer_name" name="customer[name]" value="{{ old('customer.name') }}" required minlength="2" maxlength="150" autocomplete="name"></div><div class="field"><label for="customer_phone">Telefone / WhatsApp</label><input id="customer_phone" name="customer[phone]" value="{{ old('customer.phone') }}" placeholder="+244…" type="tel" required autocomplete="tel"></div></div>
@if($product->segment->slug === 'timbragem')<div class="field"><label for="instructions">Personalização pretendida</label><textarea id="instructions" name="items[0][customization][instructions]" maxlength="1000">{{ old('items.0.customization.instructions') }}</textarea></div>@endif
<button class="button">{{ $product->purchase_mode === 'request_availability' ? 'Consultar disponibilidade' : 'Solicitar encomenda' }} ↗</button><p class="muted" style="margin-top:15px">O pedido será registado. Poderá depois abrir o WhatsApp para falar com a filial. A disponibilidade e o atendimento precisam de confirmação.</p>
</form>
@else<p>Produto apresentado para consulta. Fale com a nossa equipa para mais informações.</p><a class="button outline" href="/contacto">Contactar ↗</a>@endif
</div></div><div class="section body-copy"><h2>Sobre este produto</h2><p>{{ $product->description }}</p></div></section>
@endsection
