@extends('layouts.public')
@section('title', ($branch?->name ?? $segment->name).' — Família Gundja')
@section('content')
<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="/">Início</a> / {{ $segment->name }}</div><div class="segment-hero-wrap"><div class="segment-hero-info"><span class="eyebrow">FAZ PARTE DA NOSSA FAMÍLIA</span><h1>{{ $branch?->name ?? ($section === 'negomil-erp' ? 'NEGOMIL ERP' : $segment->name) }}</h1><p>{{ $section === 'negomil-erp' ? 'Conheça uma solução para organizar e acompanhar o seu negócio. Solicite uma demonstração à nossa equipa.' : $segment->description }}</p><div class="button-row"><a class="button" href="/{{ $segment->slug }}/produtos">Explorar produtos ↗</a><a class="text-link" href="#contactar">Fale com a equipa ↓</a></div></div>@if($segment->image)<div class="segment-hero-badge"><img src="{{ Storage::disk('public')->url($segment->image) }}" alt="Logótipo {{ $segment->name }}" class="segment-logo-badge-img"></div>@endif</div></div></section>
@if($banners->isNotEmpty())<section class="container segment-banner-showcase">@foreach($banners as $banner)<div class="segment-banner-card"><div class="segment-banner-img-wrap"><img src="{{ Storage::disk('public')->url($banner->image) }}" alt="{{ $banner->alt }}" loading="eager"></div><div class="segment-banner-caption"><div><small class="eyebrow">{{ $segment->name }}</small><h2>{{ $banner->title }}</h2><p>{{ $banner->description }}</p></div>@if($banner->target_url)<a class="button" href="{{ $banner->target_url }}">{{ $banner->button_label ?: 'Explorar' }} ↗</a>@endif</div></div>@endforeach</section>@endif
<section class="container section">
@if($branch)<div class="location-card"><span class="location-pin">⌖</span><div><small>ESTAMOS PERTO DE SI</small><h2>{{ $branch->city }}</h2><p>{{ $branch->address ?: 'Contacte a equipa para confirmar o endereço e o horário de atendimento.' }}</p>@if($branch->phone)<p><a href="tel:{{ $branch->phone }}">{{ $branch->phone }}</a></p>@endif
@if($branch->opening_hours)<div>@foreach($branch->opening_hours as $day => $hours)<p>{{ $day }}: {{ is_array($hours) ? implode(' — ', $hours) : $hours }}</p>@endforeach</div>@endif
@if($branch->latitude && $branch->longitude)<a class="text-link" href="https://www.openstreetmap.org/?mlat={{ $branch->latitude }}&mlon={{ $branch->longitude }}#map=17/{{ $branch->latitude }}/{{ $branch->longitude }}" target="_blank" rel="noopener">Ver localização ↗</a>@endif</div></div>
@else
@if($segment->slug === 'farmacia')<div class="section-heading"><div><span class="eyebrow">SAÚDE E BEM-ESTAR</span><h2>Escolha a sua farmácia.</h2></div></div><div class="location-grid">@foreach($segment->branches->where('active', true) as $location)<a class="location-card" href="/farmacia/{{ str_replace('farmacia-', '', $location->slug) }}"><span class="location-pin">⌖</span><div><small>FARMÁCIA GUNDJA</small><h3>{{ $location->city }}</h3><p>{{ $location->address ?: 'Conheça os nossos canais de atendimento.' }}</p></div><span class="circle-arrow">↗</span></a>@endforeach</div>@endif
@if($products->isNotEmpty())<div class="section-heading" style="margin-top:50px"><h2>Produtos para si.</h2><a class="text-link" href="/{{ $segment->slug }}/produtos">Ver todos ↗</a></div><div class="product-grid">@foreach($products as $product)@include('frontend.product-card')@endforeach</div>@endif
@if($services->isNotEmpty())<div class="section-heading" style="margin-top:50px"><h2>Os nossos serviços</h2></div><div class="news-grid">@foreach($services as $service)<article class="news-card"><h3>{{ $service->name }}</h3><p>{{ $service->description }}</p><p>{{ $service->price !== null ? number_format((float)$service->price,2,',','.').' Kz' : 'Sob orçamento' }}</p><a class="text-link" href="#contactar">Pedir informações ↗</a></article>@endforeach</div>@endif
@if($segment->slug === 'comercial' && $section !== 'negomil-erp')<div class="contact-band" style="margin-top:50px"><div><span class="eyebrow">GESTÃO EMPRESARIAL</span><h2>Conheça o NEGOMIL ERP.</h2></div><a href="/comercial/negomil-erp" class="button light">Solicitar demonstração ↗</a></div>@endif
@endif
</section><section class="container section" id="contactar"><div class="detail-grid"><div><span class="eyebrow">AO SEU DISPOR</span><h2>{{ $section === 'negomil-erp' ? 'Solicite uma demonstração.' : 'Como podemos ajudar?' }}</h2><p>Envie a sua mensagem. Vamos encaminhá-la à equipa de {{ $segment->name }}.</p>@if($branch?->whatsapp)<a class="button" href="https://wa.me/{{ preg_replace('/\D/', '', $branch->whatsapp) }}">Conversar no WhatsApp ↗</a>@endif</div><div>@include('frontend.contact-form', ['type' => $section === 'negomil-erp' ? 'demo' : 'quote', 'segmentId' => $segment->id, 'branchId' => $branch?->id])</div></div></section>
@include('frontend.community')
@endsection
