<?php

return [
    'produtos' => [
        'table' => 'products',
        'model' => 'App\\Models\\Product',
        'title' => 'Produtos',
        'group' => 'Catálogo',
        'permission' => 'products',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'category_id',
            'label' => 'Categoria',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => 'categories',
            'options' => null,
        ], [
            'name' => 'brand_id',
            'label' => 'Marca',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'brands',
            'options' => null,
        ], [
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sku',
            'label' => 'SKU',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'barcode',
            'label' => 'Código de barras',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'short_description',
            'label' => 'Descrição curta',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'description',
            'label' => 'Descrição',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'price',
            'label' => 'Preço (Kz)',
            'type' => 'number',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sale_price',
            'label' => 'Preço promocional (Kz)',
            'type' => 'number',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'cost_price',
            'label' => 'Custo (Kz)',
            'type' => 'number',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'unit',
            'label' => 'Unidade',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'unit' => 'Unidade',
                'litre' => 'Litro',
                'kg' => 'Quilograma',
                'metre' => 'Metro',
            ],
        ], [
            'name' => 'purchase_mode',
            'label' => 'Modo de atendimento',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'whatsapp' => 'Pedido via WhatsApp',
                'catalog_only' => 'Apenas catálogo',
                'request_availability' => 'Consultar disponibilidade',
            ],
        ], [
            'name' => 'featured',
            'label' => 'Destaque',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'categorias' => [
        'table' => 'categories',
        'model' => 'App\\Models\\Category',
        'title' => 'Categorias',
        'group' => 'Catálogo',
        'permission' => 'categories',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'parent_id',
            'label' => 'Categoria superior',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'categories',
            'options' => null,
        ], [
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'description',
            'label' => 'Descrição',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sort_order',
            'label' => 'Ordem',
            'type' => 'number',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'marcas' => [
        'table' => 'brands',
        'model' => 'App\\Models\\Brand',
        'title' => 'Marcas',
        'group' => 'Catálogo',
        'permission' => 'brands',
        'readonly' => false,
        'fields' => [[
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'filiais' => [
        'table' => 'branches',
        'model' => 'App\\Models\\Branch',
        'title' => 'Filiais',
        'group' => 'Empresa',
        'permission' => 'branches',
        'readonly' => false,
        'fields' => [[
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'city',
            'label' => 'Cidade',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'province',
            'label' => 'Província',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'address',
            'label' => 'Endereço',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'phone',
            'label' => 'Telefone',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'whatsapp',
            'label' => 'WhatsApp',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'email',
            'label' => 'Email',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'latitude',
            'label' => 'Latitude',
            'type' => 'number',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'longitude',
            'label' => 'Longitude',
            'type' => 'number',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'opening_hours',
            'label' => 'Horário de funcionamento',
            'type' => 'json',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'segment_ids',
            'label' => 'Segmentos atendidos',
            'type' => 'multiselect',
            'target' => 'segments',
            'required' => true,
            'nullable' => false,
            'options' => null,
        ]],
    ],
    'segmentos' => [
        'table' => 'segments',
        'model' => 'App\\Models\\Segment',
        'title' => 'Segmentos',
        'group' => 'Empresa',
        'permission' => 'segments',
        'readonly' => false,
        'fields' => [[
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'description',
            'label' => 'Descrição',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sort_order',
            'label' => 'Ordem',
            'type' => 'number',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'servicos' => [
        'table' => 'services',
        'model' => 'App\\Models\\Service',
        'title' => 'Serviços',
        'group' => 'Empresa',
        'permission' => 'services',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'description',
            'label' => 'Descrição',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'price',
            'label' => 'Preço (Kz)',
            'type' => 'number',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'equipa' => [
        'table' => 'team_members',
        'model' => 'App\\Models\\TeamMember',
        'title' => 'Equipa',
        'group' => 'Empresa',
        'permission' => 'team',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'branch_id',
            'label' => 'Filial',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'branches',
            'options' => null,
        ], [
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'position',
            'label' => 'Cargo',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'bio',
            'label' => 'Biografia',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sort_order',
            'label' => 'Ordem',
            'type' => 'number',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'clientes' => [
        'table' => 'customers',
        'model' => 'App\\Models\\Customer',
        'title' => 'Clientes',
        'group' => 'Negócio',
        'permission' => 'customers',
        'readonly' => false,
        'fields' => [[
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'phone',
            'label' => 'Telefone',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'email',
            'label' => 'Email',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'company',
            'label' => 'Empresa',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'notes',
            'label' => 'Notas internas',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ]],
    ],
    'noticias' => [
        'table' => 'posts',
        'model' => 'App\\Models\\Post',
        'title' => 'Notícias',
        'group' => 'Website',
        'permission' => 'content',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'title',
            'label' => 'Título',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'excerpt',
            'label' => 'Resumo',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'content',
            'label' => 'Conteúdo',
            'type' => 'textarea',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'status',
            'label' => 'Estado',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'draft' => 'Rascunho',
                'published' => 'Publicado',
            ],
        ], [
            'name' => 'published_at',
            'label' => 'Publicar em',
            'type' => 'datetime-local',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ]],
    ],
    'paginas' => [
        'table' => 'pages',
        'model' => 'App\\Models\\Page',
        'title' => 'Páginas',
        'group' => 'Website',
        'permission' => 'content',
        'readonly' => false,
        'fields' => [[
            'name' => 'title',
            'label' => 'Título',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'slug',
            'label' => 'Endereço amigável',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'content',
            'label' => 'Conteúdo',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'status',
            'label' => 'Estado',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'draft' => 'Rascunho',
                'published' => 'Publicado',
            ],
        ], [
            'name' => 'seo_title',
            'label' => 'Título SEO',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'seo_description',
            'label' => 'Descrição SEO',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'published_at',
            'label' => 'Publicar em',
            'type' => 'datetime-local',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ]],
    ],
    'banners' => [
        'table' => 'banners',
        'model' => 'App\\Models\\Banner',
        'title' => 'Banners',
        'group' => 'Website',
        'permission' => 'content',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'title',
            'label' => 'Título',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'description',
            'label' => 'Descrição',
            'type' => 'textarea',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'alt',
            'label' => 'Texto alternativo',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'button_label',
            'label' => 'Texto do botão',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'target_url',
            'label' => 'Destino do botão',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'placement',
            'label' => 'Local de exibição',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'homepage' => 'Homepage',
                'segment' => 'Segmento',
            ],
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sort_order',
            'label' => 'Ordem',
            'type' => 'number',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'starts_at',
            'label' => 'Início',
            'type' => 'datetime-local',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'ends_at',
            'label' => 'Fim',
            'type' => 'datetime-local',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ]],
    ],
    'faq' => [
        'table' => 'faqs',
        'model' => 'App\\Models\\Faq',
        'title' => 'Perguntas frequentes',
        'group' => 'Website',
        'permission' => 'content',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'question',
            'label' => 'Pergunta',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'answer',
            'label' => 'Resposta',
            'type' => 'textarea',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sort_order',
            'label' => 'Ordem',
            'type' => 'number',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'depoimentos' => [
        'table' => 'testimonials',
        'model' => 'App\\Models\\Testimonial',
        'title' => 'Depoimentos',
        'group' => 'Website',
        'permission' => 'content',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'content',
            'label' => 'Conteúdo',
            'type' => 'textarea',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'image',
            'label' => 'Imagem',
            'type' => 'image',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'active',
            'label' => 'Publicado / ativo',
            'type' => 'checkbox',
            'required' => false,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'consented_at',
            'label' => 'Autorização do depoimento',
            'type' => 'datetime-local',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'sort_order',
            'label' => 'Ordem',
            'type' => 'number',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ]],
    ],
    'contactos' => [
        'table' => 'contacts',
        'model' => 'App\\Models\\Contact',
        'title' => 'Contactos',
        'group' => 'Negócio',
        'permission' => 'contacts',
        'readonly' => false,
        'fields' => [[
            'name' => 'segment_id',
            'label' => 'Segmento',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'segments',
            'options' => null,
        ], [
            'name' => 'branch_id',
            'label' => 'Filial',
            'type' => 'select',
            'required' => false,
            'nullable' => true,
            'target' => 'branches',
            'options' => null,
        ], [
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'email',
            'label' => 'Email',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'phone',
            'label' => 'Telefone',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'company',
            'label' => 'Empresa',
            'type' => 'text',
            'required' => false,
            'nullable' => true,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'type',
            'label' => 'Tipo',
            'type' => 'text',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'general' => 'Geral',
                'demo' => 'Demonstração',
                'quote' => 'Orçamento',
            ],
        ], [
            'name' => 'message',
            'label' => 'Mensagem',
            'type' => 'textarea',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => null,
        ], [
            'name' => 'status',
            'label' => 'Estado',
            'type' => 'select',
            'required' => true,
            'nullable' => false,
            'target' => null,
            'options' => [
                'new' => 'Novo',
                'in_progress' => 'Em tratamento',
                'closed' => 'Encerrado',
            ],
        ]],
    ],
    'stock' => [
        'table' => 'inventories',
        'model' => 'App\\Models\\Inventory',
        'title' => 'Stock por filial',
        'group' => 'Inventário',
        'permission' => 'stock',
        'readonly' => true,
        'fields' => [],
    ],
    'movimentos' => [
        'table' => 'stock_movements',
        'model' => 'App\\Models\\StockMovement',
        'title' => 'Movimentos',
        'group' => 'Inventário',
        'permission' => 'movements',
        'readonly' => true,
        'fields' => [],
    ],
    'transferencias' => [
        'table' => 'stock_transfers',
        'model' => 'App\\Models\\StockTransfer',
        'title' => 'Transferências',
        'group' => 'Inventário',
        'permission' => 'transfers',
        'readonly' => true,
        'fields' => [],
    ],
    'pedidos' => [
        'table' => 'orders',
        'model' => 'App\\Models\\Order',
        'title' => 'Pedidos',
        'group' => 'Negócio',
        'permission' => 'orders',
        'readonly' => true,
        'fields' => [],
    ],
    'logs' => [
        'table' => 'activity_logs',
        'model' => 'App\\Models\\ActivityLog',
        'title' => 'Auditoria',
        'group' => 'Sistema',
        'permission' => 'logs',
        'readonly' => true,
        'fields' => [],
    ],
    'utilizadores' => [
        'table' => 'users',
        'model' => 'App\\Models\\User',
        'title' => 'Utilizadores',
        'group' => 'Sistema',
        'permission' => 'users',
        'readonly' => false,
        'fields' => [[
            'name' => 'name',
            'label' => 'Nome',
            'type' => 'text',
            'required' => true,
        ], [
            'name' => 'email',
            'label' => 'Email',
            'type' => 'email',
            'required' => true,
        ], [
            'name' => 'password',
            'label' => 'Nova palavra-passe',
            'type' => 'password',
            'required' => false,
        ], [
            'name' => 'active',
            'label' => 'Ativo',
            'type' => 'checkbox',
            'required' => false,
        ]],
    ],
];
