<script setup>
import {computed} from 'vue';
import {Link, useForm} from '@inertiajs/vue3';
import AdminLayout from '../../Components/AdminLayout.vue';
import {states} from '../../labels';
const props=defineProps({stats:Object,days:Array,bySegment:Array,lowStock:Array,latestOrders:Array,from:String,to:String});
const form=useForm({from:props.from,to:props.to});
const max=computed(()=>Math.max(1,...props.days.map(d=>d.total)));
</script>
<template><AdminLayout>
<div class="page-heading"><div><span class="eyebrow">A SUA EMPRESA, NUM SÓ LUGAR</span><h1>Visão geral</h1><p>Acompanhe o que acontece na Família Gundja.</p></div><form class="toolbar" @submit.prevent="form.get('/admin/dashboard')"><label>De <input type="date" v-model="form.from"></label><label>Até <input type="date" v-model="form.to"></label><button class="button small">Aplicar</button></form></div>
<div class="stats"><Link class="stat" href="/admin/produtos"><small>Produtos ativos</small><div class="stat-icon">▦</div><strong>{{stats.products.toLocaleString('pt-AO')}}</strong><span>No seu âmbito de acesso</span></Link><Link class="stat" href="/admin/stock?alert=low"><small>Stock baixo</small><div class="stat-icon">↘</div><strong>{{stats.low}}</strong><span>Ocorrências por filial · atual</span></Link><Link class="stat" href="/admin/pedidos"><small>Pedidos</small><div class="stat-icon">▤</div><strong>{{stats.orders}}</strong><span>No período selecionado</span></Link><Link class="stat" href="/admin/stock?alert=low"><small>Sem stock</small><div class="stat-icon">○</div><strong>{{stats.empty}}</strong><span>Ocorrências por filial · atual</span></Link></div>
<div class="dashboard-grid"><section class="panel"><div class="panel-title"><h2>Evolução dos pedidos</h2><small>{{from}} — {{to}}</small></div><div v-if="days.length"><div class="chart-bars"><div v-for="day in days" :key="day.day" class="chart-bar" :style="{height:(Math.max(5,day.total/max*90))+'%'}" :title="day.day+': '+day.total+' pedidos'"><span>{{day.total}}</span></div></div><div class="chart-axis"><span>{{days[0].day}}</span><span>{{days.at(-1).day}}</span></div></div><div v-else class="empty-state" style="padding:35px 20px"><h3 style="font-size:17px">Ainda sem pedidos neste período.</h3><p style="font-size:12px">Os pedidos recebidos aparecerão aqui.</p></div></section>
<section class="panel"><div class="panel-title"><h2>Pedidos por segmento</h2><small>Distribuição</small></div><div v-for="segment in bySegment" :key="segment.segment_id" class="segment-row"><div><span>{{segment.segment?.name}}</span><strong>{{stats.orders ? Math.round(segment.total/stats.orders*100):0}}% <small>· {{segment.total}}</small></strong></div><div class="progress-track"><span :style="{width:(stats.orders?segment.total/stats.orders*100:0)+'%'}"></span></div></div><p v-if="!bySegment.length" class="muted">A distribuição será calculada a partir dos pedidos reais.</p></section></div>
<section class="panel"><div class="panel-title"><h2>Produtos que precisam de atenção</h2><Link href="/admin/stock?alert=low">Ver inventário ↗</Link></div><div class="table-scroll"><table><thead><tr><th>Produto</th><th>Filial</th><th>Stock atual</th><th>Mínimo</th><th>Estado</th></tr></thead><tbody><tr v-for="stock in lowStock" :key="stock.id"><td>{{stock.product?.name}}</td><td>{{stock.branch?.name}}</td><td>{{stock.quantity}}</td><td>{{stock.minimum_quantity}}</td><td><span class="badge" :class="Number(stock.quantity)===0?'error':'warning'">{{Number(stock.quantity)===0?'Sem stock':'Stock baixo'}}</span></td></tr><tr v-if="!lowStock.length"><td colspan="5" style="text-align:center;padding:28px;color:#889580">Sem alertas de stock no seu âmbito de acesso.</td></tr></tbody></table></div></section>
<section class="panel"><div class="panel-title"><h2>Pedidos recentes</h2><Link href="/admin/pedidos">Ver pedidos ↗</Link></div><div class="table-scroll"><table><thead><tr><th>Referência</th><th>Filial</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="order in latestOrders" :key="order.id"><td>{{order.public_id}}</td><td>{{order.branch?.name}}</td><td><span class="badge">{{states[order.status]}}</span></td><td><Link :href="'/admin/pedidos/'+order.id">Ver ↗</Link></td></tr><tr v-if="!latestOrders.length"><td colspan="4">Nenhum pedido recebido neste período.</td></tr></tbody></table></div></section>
</AdminLayout></template>
