<script setup>
import {computed} from 'vue';
import {Link,useForm,router} from '@inertiajs/vue3';
import AdminLayout from '../../Components/AdminLayout.vue';
import Pagination from '../../Components/Pagination.vue';
import {labels,value} from '../../labels';
const props=defineProps({resource:String,definition:Object,records:Object,filters:Object,canCreate:Boolean,canOperate:Boolean,segments:Array,branches:Array});
const form=useForm({q:props.filters.q||'',segment_id:props.filters.segment_id||'',branch_id:props.filters.branch_id||'',alert:props.filters.alert||'',status:props.filters.status||''});
const columns=computed(()=>({
 produtos:['name','sku','price','active'],categorias:['name','slug','active'],marcas:['name','active'],filiais:['name','city','phone','active'],segmentos:['name','slug','active'],
 stock:['product_id','branch_id','quantity','minimum_quantity'],movimentos:['product_id','branch_id','type','quantity','new_quantity','created_at'],transferencias:['reference','source_branch_id','destination_branch_id','status'],
 pedidos:['public_id','branch_id','status','total','created_at'],clientes:['name','phone','email'],utilizadores:['name','email','active'],noticias:['title','status','published_at'],paginas:['title','slug','status'],
 banners:['title','placement','active'],contactos:['name','type','status','created_at'],servicos:['name','price','active'],equipa:['name','position','active'],faq:['question','active'],depoimentos:['name','active'],logs:['action','model_type','model_id','created_at']
}[props.resource]||['name','created_at']));
function remove(id){if(confirm('Eliminar este registo? Cadastros com histórico devem ser desativados.'))router.delete('/admin/'+props.resource+'/'+id);}
</script>
<template><AdminLayout><div class="page-heading"><div><span class="eyebrow">{{definition.group}}</span><h1>{{definition.title}}</h1><p>{{records.total}} registos no seu âmbito de acesso.</p></div><Link v-if="canCreate" :href="'/admin/'+resource+'/criar'" class="button small">+ Novo registo</Link><Link v-if="resource==='stock'&&canOperate" href="/admin/stock/ajustar" class="button small">Ajustar stock ↗</Link><Link v-if="resource==='transferencias'&&canOperate" href="/admin/transferencias/criar" class="button small">+ Transferência</Link></div>
<div class="panel"><form class="toolbar" @submit.prevent="form.get('/admin/'+resource)"><input v-model="form.q" class="search-input" placeholder="Pesquisar por nome…" aria-label="Pesquisar"><select v-model="form.segment_id" aria-label="Filtrar por segmento"><option value="">Todos os segmentos</option><option v-for="s in segments" :key="s.id" :value="s.id">{{s.name}}</option></select><select v-model="form.branch_id" aria-label="Filtrar por filial"><option value="">Todas as filiais</option><option v-for="b in branches" :key="b.id" :value="b.id">{{b.name}}</option></select><select v-if="resource==='stock'" v-model="form.alert" aria-label="Alerta de stock"><option value="">Todos os saldos</option><option value="low">Stock baixo</option><option value="zero">Stock zero</option><option value="uncounted">Sem contagem</option></select><select v-if="resource==='transferencias'" v-model="form.status" aria-label="Estado"><option value="">Todos os estados</option><option value="draft">Rascunho</option><option value="dispatched">Em trânsito</option><option value="received">Recebido</option><option value="cancelled">Cancelado</option></select><button class="button outline small">Pesquisar</button><Link :href="'/admin/'+resource" class="muted">Limpar</Link></form>
<div class="table-scroll"><table><thead><tr><th v-for="column in columns" :key="column">{{labels[column]||column}}</th><th>Ações</th></tr></thead><tbody><tr v-for="row in records.data" :key="row.id"><td v-for="column in columns" :key="column"><span :class="{badge:['status','active'].includes(column)}">{{value(row,column)}}</span></td><td><div class="actions"><Link v-if="!definition.readonly&&row.can_update&&resource!=='contactos'" :href="'/admin/'+resource+'/'+row.id+'/editar'">Editar ↗</Link><Link v-if="['pedidos','transferencias','contactos'].includes(resource)" :href="'/admin/'+resource+'/'+row.id">Abrir ↗</Link><button v-if="!definition.readonly&&row.can_delete&&!['utilizadores','clientes','contactos'].includes(resource)" @click="remove(row.id)">Eliminar</button><span v-if="definition.readonly&&!['pedidos','transferencias','contactos'].includes(resource)" class="muted">—</span></div></td></tr></tbody></table></div><div v-if="!records.data.length" class="empty-state"><h3>Nenhum registo encontrado.</h3><p>Os dados cadastrados aparecerão aqui.</p></div><Pagination :links="records.links"/></div></AdminLayout></template>
