<script setup>
import {computed} from 'vue';
import {Head,useForm,usePoll} from '@inertiajs/vue3';
import AdminLayout from '../../Components/AdminLayout.vue';
import Pagination from '../../Components/Pagination.vue';
const props=defineProps({records:Object,filters:Object,segments:Array,branches:Array,exports:Array,types:Array});
const names={stock:'Posição atual de stock',movements:'Movimentos de stock',orders:'Pedidos e valores cotados',products:'Produtos',segments:'Resumo por segmento',branches:'Resumo por filial'};
const form=useForm({type:props.filters.type,from:props.filters.from||'',to:props.filters.to||'',segment_id:props.filters.segment_id||'',branch_id:props.filters.branch_id||''});
const columns=computed(()=>Object.keys(props.records.data[0]||{}));
const exporting=useForm({});
usePoll(5000,{only:['exports']},{autoStart:true});
</script>
<template><AdminLayout><Head title="Relatórios"/><div class="page-heading"><div><span class="eyebrow">Análise</span><h1>Relatórios</h1><p>Stock representa o saldo atual. Pedidos representam valores cotados, sem contabilizar vendas.</p></div></div><form class="panel admin-form" @submit.prevent="form.get('/admin/relatorios')"><div class="form-grid"><div class="field"><label for="report-type">Relatório</label><select id="report-type" v-model="form.type"><option v-for="t in types||Object.keys(names)" :key="t" :value="t">{{names[t]}}</option></select></div><div class="field"><label for="report-segment">Segmento</label><select id="report-segment" v-model="form.segment_id"><option value="">Todos autorizados</option><option v-for="s in segments" :key="s.id" :value="s.id">{{s.name}}</option></select></div><div class="field"><label for="report-branch">Filial</label><select id="report-branch" v-model="form.branch_id"><option value="">Todas autorizadas</option><option v-for="b in branches" :key="b.id" :value="b.id">{{b.name}}</option></select></div><template v-if="['orders','movements','segments','branches'].includes(form.type)"><div class="field"><label for="report-from">De</label><input id="report-from" type="date" v-model="form.from"></div><div class="field"><label for="report-to">Até</label><input id="report-to" type="date" v-model="form.to" :min="form.from"></div></template></div><div class="button-row"><button class="button" :disabled="form.processing">Aplicar filtros</button><button class="button outline" type="button" :disabled="exporting.processing" @click="exporting.transform(()=>form.data()).post('/admin/exportacoes')">Preparar exportação CSV</button></div></form><section class="panel"><div class="table-scroll"><table v-if="records.data.length"><thead><tr><th v-for="col in columns" :key="col">{{col}}</th></tr></thead><tbody><tr v-for="(row,i) in records.data" :key="i"><td v-for="col in columns" :key="col">{{row[col]??'—'}}</td></tr></tbody></table></div><p v-if="!records.data.length" class="empty-state">Nenhum resultado para os filtros selecionados.</p><Pagination :links="records.links"/></section><section class="panel admin-form"><h2>Exportações privadas</h2><p class="muted">Os ficheiros expiram em 24 horas e exigem o mesmo acesso do relatório.</p><div v-for="e in exports" :key="e.id" class="access-card actions"><span>{{names[e.type]}} · {{new Date(e.created_at).toLocaleString('pt-AO')}} · {{({pending:'Na fila',processing:'A gerar',completed:'Disponível',failed:'Falhou'})[e.status]}}</span><a v-if="e.url" :href="e.url">Descarregar CSV ↓</a><span v-if="e.error">{{e.error}}</span></div><p v-if="!exports?.length">Nenhuma exportação solicitada.</p></section></AdminLayout></template>
